FROM python:3.12-slim

WORKDIR /app

COPY requirements-ui.txt ./requirements-ui.txt
RUN pip install --no-cache-dir -r requirements-ui.txt

COPY src/ui/ui_app.py ./ui_app.py
COPY src/ui/ui_templates ./ui_templates
COPY src/ui/ui_static ./ui_static

EXPOSE 8080

CMD ["uvicorn", "ui_app:app", "--host", "0.0.0.0", "--port", "8080"]
