apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-info
  namespace: empl-attr
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  POSTGRES_DB: "attr_db"
  POSTGRES_USER: user1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: empl-attr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      volumes:
      - name: postgres-data
        hostPath:
          path: /mnt/storage/postgres
          type: DirectoryOrCreate

      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
          - configMapRef:
              name: postgres-info

          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: empl-attr

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP