name: CI

on:
  push:
  pull_request:
    branches:
      - develop
      - main


permissions:
  contents: read
  packages: write

jobs:
  push-tests:
    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          pip install flake8 black pytest

      - name: Check formatting
        run: black --check src tests notebooks

      - name: lint
        run: flake8 src tests

      - name: tests
        run: pytest tests

      - name: Build predictor app image
        run: docker build -t predictor-app:ci -f Dockerfile.predictor .

      #- name: Run predictor app
      #  run: |
      #    docker run \
      #    -d --name predictor-app \
      #    -p 8000:8000 predictor-app:ci

      #- name: Wait for app
      #  run: |
      #    for i in {1..30}; do
      #      if curl -f http://localhost:8000/health; then
      #        exit 0
      #      fi
      #      sleep 2
      #    done
      #    docker logs predictor-app
      #    exit 1

      #- name: Stop container
      #  if: always()
      #  run: docker rm -f predictor-app

      - name: Build UI app image
        run: docker build -t ui-app:ci -f Dockerfile.ui .

      - name: Run UI app
        run: |
          docker run \
          -d --name ui-app \
          -p 8080:8080 ui-app:ci

      - name: Wait for UI app
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/inference; then
              exit 0
            fi
            sleep 2
          done
          docker logs ui-app
          exit 1

      - name: Stop UI container
        if: always()
        run: docker rm -f ui-app

  main-merge-tests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          pip install flake8 black pytest

      - name: Check formatting
        run: black --check src tests notebooks

      - name: lint
        run: flake8 src tests

      - name: tests
        run: pytest tests

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/predictor-app:latest -f Dockerfile.predictor .

      #- name: Run predictor app
      #  run: |
      #    docker run \
      #    -d --name predictor-app \
      #    -p 8000:8000 ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/predictor-app:latest

      #- name: Wait for app
      #  run: |
      #    for i in {1..30}; do
      #      if curl -f http://localhost:8000/health; then
      #        exit 0
      #      fi
      #      sleep 2
      #    done
      #    docker logs predictor-app
      #    exit 1

      #- name: Stop container
      #  if: always()
      #  run: docker rm -f predictor-app

      - name: Push image
        run: docker push ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/predictor-app:latest


      - name: Build UI image
        run: docker build -t ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/ui-app:latest -f Dockerfile.ui .

      - name: Run UI app
        run: |
          docker run \
          -d --name ui-app \
          -p 8080:8080 ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/ui-app:latest

      - name: Wait for UI app
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/inference; then
              exit 0
            fi
            sleep 2
          done
          docker logs ui-app
          exit 1

      - name: Stop UI container
        if: always()
        run: docker rm -f ui-app

      - name: Push UI image
        run: docker push ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/ui-app:latest


      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: lr_mlops/predictor-app
          package-type: container
          min-versions-to-keep: 3


      - name: Delete old UI package versions
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: lr_mlops/ui-app
          package-type: container
          min-versions-to-keep: 3